version: "2.0"

services:
  solr-engine:
    image: solr:7.1
    ports:
     - "8983:8983"
    networks:
      - backend
  recommendation-system-app:
    build: recommendation-system-app/
    image: recommendation-system-app:0.1.0
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
