version: "2.0"

services:
  solr-engine:
    image: solr:7.1
    ports:
     - "8983:8983"
    networks:
      - backend

  recommendation-system-app:
    build:
      context: recommendation-system-app/
    image: recommendation-system-app:0.1.0
    working_dir: /var/www/recommendation-system-app
    volumes:
      - ./recommendation-system-app/:/var/www/recommendation-system-app/
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
