version: '3.4'

services:
  recommendation-system-app:
    build:
      context: recommendation-system-app/
    image: recommendation-system-app:0.1.0
    working_dir: /var/www/recommendation-system-app
    env_file: ./recommendation-system-app/.env
    depends_on:
      - recommendation-system-engine
    networks:
      - backend
    ports:
      - 8080:80
    volumes:
      - ./recommendation-system-app/:/var/www/recommendation-system-app/
  recommendation-system-engine:
    restart: on-failure
    build:
      context: recommendation-system-engine/
    image: recommendation-system-engine:0.1.0
    working_dir: /var/www/recommendation-system-engine
    ports:
      - 5000:5000
    volumes:
      - ./recommendation-system-engine/:/var/www/recommendation-system-engine/
    networks:
      - backend
      - mongodb
  mongodb:
    restart: always
    image: mongo:3.6-jessie
    volumes:
      - type: volume
        source: mongo-config
        target: /data/configdb
      - type: volume
        source: mongo-data
        target: /data/db
    networks:
      - mongodb
networks:
  backend:
    driver: bridge
  mongodb:
    driver: bridge
volumes:
  mongo-data:
  mongo-config:
