version: '3.4'

services:
  recommendation-system-app:
    build:
      context: recommendation-system-app/
    image: recommendation-system-app:0.1.0
    working_dir: /var/www/recommendation-system-app
    volumes:
      - ./recommendation-system-app/:/var/www/recommendation-system-app/
    networks:
      - backend
    ports:
      - 8080:80
  recommendation-system-engine:
    build:
      context: recommendation-system-engine/
    image: recommendation-system-engine:0.1.0
    working_dir: /var/www/recommendation-system-engine
    expose:
      - 5000
    volumes:
      - ./recommendation-system-engine/:/var/www/recommendation-system-engine/
    networks:
      - backend
      - mongodb
  mongodb:
    image: mongo:3.6-jessie
    ports:
      - 27017:27017
    networks:
      - mongodb
networks:
  backend:
    driver: bridge
  mongodb:
    driver: bridge

volumes:
  data:
