version: '3.4'

services:
  mongodb:
    image: mongo:3.6-jessie
    ports:
      - 27017:27017
    networks:
      - mongodb

  recommendation-system-app:
    build:
      context: recommendation-system-app/
    image: recommendation-system-app:0.1.0
    working_dir: /var/www/recommendation-system-app
    volumes:
      - ./recommendation-system-app/:/var/www/recommendation-system-app/
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
  mongodb:
    driver: bridge

volumes:
  data:
