# coding=utf-8
from flask import current_app
from bson.json_util import loads
import glob, json, os

def get_users_collection(client):
    return client.db.users

def get_events_collection(client):
    return client.db.events

def init_events_collection(client):
    collection = get_events_collection(client)
    collection.delete_many({})
    data_dir = current_app.config['DATA_DIR']
    for json_file in glob.glob(os.path.join(data_dir, '*.json')):
        events = json.load(open(json_file))
        collection.insert_many(events)

def init_users_collection(client):
    collection = get_users_collection(client)
    collection.delete_many({})
    collection.insert_many([
        {
            'firstname': 'Mario',
            'lastname' : 'Rossi',
            'gender' : 'M',
            'city' : 'Milano',
            'age' : 25,
            'avatar': 'https://tinyfac.es/data/avatars/BA0CB1F2-8C79-4376-B13B-DD5FB8772537-200w.jpeg',
            'categories_distribution' : [0.6, 0.2, 0.1, 0.1, 0],
        },
        {
            'firstname': 'Francesca',
            'lastname' : 'Trello',
            'gender' : 'F',
            'city' : 'Milano',
            'age' : 17,
            'avatar': 'https://tinyfac.es/data/avatars/03F55412-DE8A-4F83-AAA6-D67EE5CE48DA-200w.jpeg',
            'categories_distribution' : [0, 0.2, 0.3, 0, 0.5],
        },
        {
            'firstname': 'Andrea',
            'lastname' : 'Rotin',
            'gender' : 'M',
            'city' : 'Milano',
            'age' : 36,
            'avatar': 'https://tinyfac.es/data/avatars/B3CF5288-34B0-4A5E-9877-5965522529D6-200w.jpeg',
            'categories_distribution' : [0.6, 0.1, 0.3, 0, 0],
        },
        {
            'firstname': 'Marta',
            'lastname' : 'Zaini',
            'gender' : 'F',
            'city' : 'Milano',
            'age' : 22,
            'avatar': 'https://tinyfac.es/data/avatars/A7299C8E-CEFC-47D9-939A-3C8CA0EA4D13-200w.jpeg',
            'categories_distribution' : [0.2, 0.2, 0.2, 0.2, 0.2],
        },
        {
            'firstname': 'Annalisa',
            'lastname' : 'Poteri',
            'gender' : 'F',
            'city' : 'Milano',
            'age' : 45,
            'avatar': 'https://tinyfac.es/data/avatars/A7299C8E-CEFC-47D9-939A-3C8CA0EA4D13-200w.jpeg',
            'categories_distribution' : [0, 0.4, 0.4, 0.05, 0.15],
        },
        {
            'firstname': 'Alessandro',
            'lastname' : 'Vaghi',
            'gender' : 'M',
            'city' : 'Roma',
            'age' : 19,
            'avatar': 'https://tinyfac.es/data/avatars/2DDDE973-40EC-4004-ABC0-73FD4CD6D042-200w.jpeg',
            'categories_distribution' : [0.25, 0.35, 0.3, 0.05, 0.05],
        },
        {
            'firstname': 'Matteo',
            'lastname' : 'Tundo',
            'gender' : 'M',
            'city' : 'Roma',
            'age' : 38,
            'avatar': 'https://tinyfac.es/data/avatars/344CFC24-61FB-426C-B3D1-CAD5BCBD3209-200w.jpeg',
            'categories_distribution' : [1, 0, 0, 0, 0],
        },
        {
            'firstname': 'Alice',
            'lastname' : 'Perla',
            'gender' : 'F',
            'city' : 'Roma',
            'age' : 20,
            'avatar': 'https://tinyfac.es/data/avatars/03F55412-DE8A-4F83-AAA6-D67EE5CE48DA-200w.jpeg',
            'categories_distribution' : [0.8, 0.2, 0, 0, 0],
        },
        {
            'firstname': 'Milena',
            'lastname' : 'Gabanelli',
            'gender' : 'F',
            'city' : 'Roma',
            'age' : 29,
            'avatar': 'https://tinyfac.es/data/avatars/A7299C8E-CEFC-47D9-939A-3C8CA0EA4D13-200w.jpeg',
            'categories_distribution' : [0.2, 0.2, 0.5, 0.1, 0],
        },
        {
            'firstname': 'Riccardo',
            'lastname' : 'Volentis',
            'gender' : 'M',
            'city' : 'Roma',
            'age' : 51,
            'avatar': 'https://tinyfac.es/data/avatars/BA0CB1F2-8C79-4376-B13B-DD5FB8772537-200w.jpeg',
            'categories_distribution' : [0.5, 0.4, 0.1, 0, 0],
        },
        {
            'firstname': 'Riccardino',
            'lastname' : 'Fuffolo',
            'gender' : 'M',
            'city' : 'Milano',
            'age' : 23,
            'avatar': 'https://tinyfac.es/data/avatars/344CFC24-61FB-426C-B3D1-CAD5BCBD3209-200w.jpeg',
            'categories_distribution' : [0.05, 0.05, 0.7, 0.1, 0.1],
        },
        {
            'firstname': 'Dario',
            'lastname' : 'Fumagalli',
            'gender' : 'M',
            'city' : 'Milano',
            'age' : 37,
            'avatar': 'https://tinyfac.es/data/avatars/344CFC24-61FB-426C-B3D1-CAD5BCBD3209-200w.jpeg',
            'categories_distribution' : [0.75, 0.15, 0.05, 0.05, 0],
        },
        {
            'firstname': 'Valeria',
            'lastname' : 'Marini',
            'gender' : 'F',
            'city' : 'Milano',
            'age' : 19,
            'avatar': 'https://tinyfac.es/data/avatars/A7299C8E-CEFC-47D9-939A-3C8CA0EA4D13-200w.jpeg',
            'categories_distribution' : [0, 0.2, 0.05, 0.1, 0.65],
        },
        {
            'firstname': 'Franca',
            'lastname' : 'Uccheddu',
            'gender' : 'F',
            'city' : 'Milano',
            'age' : 47,
            'avatar': 'https://tinyfac.es/data/avatars/A7299C8E-CEFC-47D9-939A-3C8CA0EA4D13-200w.jpeg',
            'categories_distribution' : [0, 0, 0.6, 0.1, 0.3],
        },
        {
            'firstname': 'Piero',
            'lastname' : 'Fumagalli',
            'gender' : 'M',
            'city' : 'Milano',
            'age' : 23,
            'avatar': 'https://tinyfac.es/data/avatars/344CFC24-61FB-426C-B3D1-CAD5BCBD3209-200w.jpeg',
            'categories_distribution' : [0.4, 0.1, 0.5, 0, 0],
        },
        {
            'firstname': 'Ennio',
            'lastname' : 'Annio',
            'gender' : 'M',
            'city' : 'Roma',
            'age' : 35,
            'avatar': 'https://tinyfac.es/data/avatars/344CFC24-61FB-426C-B3D1-CAD5BCBD3209-200w.jpeg',
            'categories_distribution' : [0.05, 0.1, 0, 0.05, 0.8],
        },
        {
            'firstname': 'Augusto',
            'lastname' : 'Colonna',
            'gender' : 'M',
            'city' : 'Roma',
            'age' : 58,
            'avatar': 'https://tinyfac.es/data/avatars/344CFC24-61FB-426C-B3D1-CAD5BCBD3209-200w.jpeg',
            'categories_distribution' : [0.25, 0, 0, 0, 0.75],
        },
        {
            'firstname': 'Flavia',
            'lastname' : 'Spada',
            'gender' : 'F',
            'city' : 'Roma',
            'age' : 29,
            'avatar': 'https://tinyfac.es/data/avatars/A7299C8E-CEFC-47D9-939A-3C8CA0EA4D13-200w.jpeg',
            'categories_distribution' : [0.33, 0.47, 0.1, 0.1, 0],
        },
        {
            'firstname': 'Maurizia',
            'lastname' : 'Odescalchi',
            'gender' : 'F',
            'city' : 'Roma',
            'age' : 33,
            'avatar': 'https://tinyfac.es/data/avatars/A7299C8E-CEFC-47D9-939A-3C8CA0EA4D13-200w.jpeg',
            'categories_distribution' : [0.2, 0.6, 0.1, 0.04, 0.06],
        },
        {
            'firstname': 'Nadia',
            'lastname' : 'Orsini',
            'gender' : 'F',
            'city' : 'Roma',
            'age' : 42,
            'avatar': 'https://tinyfac.es/data/avatars/A7299C8E-CEFC-47D9-939A-3C8CA0EA4D13-200w.jpeg',
            'categories_distribution' : [0.6, 0.2, 0.1, 0.1, 0],
        },
        {
            'firstname': 'Piero',
            'lastname' : 'Sforza',
            'gender' : 'M',
            'city' : 'Milano',
            'age' : 39,
            'avatar': 'https://tinyfac.es/data/avatars/344CFC24-61FB-426C-B3D1-CAD5BCBD3209-200w.jpeg',
            'categories_distribution' : [0.22, 0.28, 0.3, 0.1, 0.1],
        },
        {
            'firstname': 'Roberto',
            'lastname' : 'Villa',
            'gender' : 'M',
            'city' : 'Milano',
            'age' : 29,
            'avatar': 'https://tinyfac.es/data/avatars/344CFC24-61FB-426C-B3D1-CAD5BCBD3209-200w.jpeg',
            'categories_distribution' : [0.6, 0.1, 0.2, 0, 0.1],
        },
        {
            'firstname': 'Martina',
            'lastname' : 'Mariani',
            'gender' : 'F',
            'city' : 'Milano',
            'age' : 46,
            'avatar': 'https://tinyfac.es/data/avatars/A7299C8E-CEFC-47D9-939A-3C8CA0EA4D13-200w.jpeg',
            'categories_distribution' : [0.1, 0.1, 0, 0, 0.8],
        },
        {
            'firstname': 'Sara',
            'lastname' : 'Fumagalli',
            'gender' : 'F',
            'city' : 'Milano',
            'age' : 34,
            'avatar': 'https://tinyfac.es/data/avatars/A7299C8E-CEFC-47D9-939A-3C8CA0EA4D13-200w.jpeg',
            'categories_distribution' : [0.2, 0.1, 0.1, 0.4, 0.2],
        },
        {
            'firstname': 'Carlo',
            'lastname' : 'Ventura',
            'gender' : 'M',
            'city' : 'Milano',
            'age' : 53,
            'avatar': 'https://tinyfac.es/data/avatars/344CFC24-61FB-426C-B3D1-CAD5BCBD3209-200w.jpeg',
            'categories_distribution' : [0.2, 0, 0.2, 0.3, 0.3],
        },
        {
            'firstname': 'Gianfranco',
            'lastname' : 'Funari',
            'gender' : 'M',
            'city' : 'Roma',
            'age' : 55,
            'avatar': 'https://tinyfac.es/data/avatars/344CFC24-61FB-426C-B3D1-CAD5BCBD3209-200w.jpeg',
            'categories_distribution' : [1, 0, 0, 0, 0],
        },
        {
            'firstname': 'Giulio',
            'lastname' : 'Cesarone',
            'gender' : 'M',
            'city' : 'Roma',
            'age' : 58,
            'avatar': 'https://tinyfac.es/data/avatars/344CFC24-61FB-426C-B3D1-CAD5BCBD3209-200w.jpeg',
            'categories_distribution' : [0, 0, 0.05, 0.45, 0.5],
        },
        {
            'firstname': 'Laura',
            'lastname' : 'Taverna',
            'gender' : 'F',
            'city' : 'Roma',
            'age' : 30,
            'avatar': 'https://tinyfac.es/data/avatars/A7299C8E-CEFC-47D9-939A-3C8CA0EA4D13-200w.jpeg',
            'categories_distribution' : [0.5, 0.3, 0.1, 0.1, 0],
        },
        {
            'firstname': 'Alice',
            'lastname' : 'Morelli',
            'gender' : 'F',
            'city' : 'Roma',
            'age' : 35,
            'avatar': 'https://tinyfac.es/data/avatars/A7299C8E-CEFC-47D9-939A-3C8CA0EA4D13-200w.jpeg',
            'categories_distribution' : [0.2, 0.2, 0.06, 0.04, 0.5],
        },
        {
            'firstname': 'Alessandra',
            'lastname' : 'Baricco',
            'gender' : 'F',
            'city' : 'Roma',
            'age' : 20,
            'avatar': 'https://tinyfac.es/data/avatars/A7299C8E-CEFC-47D9-939A-3C8CA0EA4D13-200w.jpeg',
            'categories_distribution' : [0.3, 0.1, 0.2, 0.3, 0.1],
        },
    ])
